version: '3'
services:
  postgresql:
    container_name: postgresql
    image: postgres:13.6
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker/postgresql/data:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    hostname: postgres
    user: postgres
  pg-web:
    image: sosedoff/pgweb
    container_name: pg-web
    ports:
      - '8800:8081'
    environment:
      PGWEB_DATABASE_URL: postgres://postgres:postgres@postgres:5432/develop?sslmode=disable
    depends_on:
      - postgresql
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: ${BUILD_TARGET:-dev}
    container_name: app
    environment:
      - GOPATH=/go
      - DB_HOST=postgresql
      - SERVER_HOST=0.0.0.0
    volumes:
      - ./:/go/src/app
    ports:
      - '8080:8080'
    tty: true
    depends_on:
      - postgresql
volumes:
  db_data:
    external: false